# kubernetes deployment for 0x524c/echo-server image

apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-test
  namespace: multpex
spec:
  selector:
    matchLabels:
      app: front-test
  replicas: 1
  template:
    metadata:
      labels:
        app: front-test
    spec:
      containers:
        - name: front-test
          image: 0x524c/front-test:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: front-test
  namespace: multpex
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: front-test
