apiVersion: v1
items:
  - apiVersion: gateway.networking.k8s.io/v1beta1
    kind: ReferenceGrant
    metadata:
      name: allow-httproute-in-multpex
      namespace: multpex
    spec:
      from:
        - group: gateway.networking.k8s.io
          kind: HTTPRoute
          namespace: istio-system
      to:
        - group: ""
          kind: Service
kind: List
metadata:
  resourceVersion: ""
