apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: front-test
  namespace: istio-system
spec:
  parentRefs:
    - name: gateway-istio
      namespace: istio-system
      sectionName: https
  hostnames: ["front-test.devops.multpex.com.br"]
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: front-test
          namespace: default
          port: 3000
          weight: 100
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: front-test-http-redirect
  namespace: istio-system
spec:
  parentRefs:
    - name: gateway-istio
      namespace: istio-system
      sectionName: http
  hostnames: ["front-test.devops.multpex.com.br"]
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: api
  namespace: istio-system
spec:
  parentRefs:
    - name: gateway-istio
      namespace: istio-system
      sectionName: https
  hostnames: ["api-sync.devops.multpex.com.br"]
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: api
          namespace: default
          port: 4000
          weight: 100
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: api-http-redirect
  namespace: istio-system
spec:
  parentRefs:
    - name: gateway-istio
      namespace: istio-system
      sectionName: http
  hostnames: ["api-sync.devops.multpex.com.br"]
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
