apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: dashboard
  namespace: istio-system
spec:
  parentRefs:
    - name: gateway-istio
      namespace: istio-system
      sectionName: https
  hostnames: ["echo-server.devops.multpex.com.br"]
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: dashboard
          namespace: labs
          port: 3000
          weight: 100
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: labs-http-redirect
  namespace: istio-system
spec:
  parentRefs:
    - name: gateway-istio
      namespace: istio-system
      sectionName: http
  hostnames: ["labs.devops.multpex.com.br"]
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: api
  namespace: istio-system
spec:
  parentRefs:
    - name: gateway-istio
      namespace: istio-system
      sectionName: https
  hostnames: ["api.devops.multpex.com.br"]
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: api
          namespace: labs
          port: 4000
          weight: 100
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: api-http-redirect
  namespace: istio-system
spec:
  parentRefs:
    - name: gateway-istio
      namespace: istio-system
      sectionName: http
  hostnames: ["api.devops.multpex.com.br"]
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
