# dashboard service
apiVersion: v1
kind: Service
metadata:
  name: front-test
  labels:
    app: front-test
    service: front-test
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: front-test
---
# broker service
apiVersion: v1
kind: Service
metadata:
  name: api-sync
  labels:
    app: api-sync
    service: api-sync
spec:
  selector:
    app: api
  ports:
    - name: http
      protocol: TCP
      appProtocol: kubernetes.io/ws
      port: 4000
      targetPort: 4000
    - name: prometheus
      protocol: TCP
      port: 3030
      targetPort: 3030
---
apiVersion: v1
kind: Service
metadata:
  name: nats
spec:
  selector:
    app: nats
  ports:
    - port: 4222
      name: nats
      targetPort: 4222
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      name: redis
      targetPort: 6379
