apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multpex
  namespace: argocd
spec:
  destination:
    namespace: multpex
    server: https://kubernetes.default.svc
  project: default
  source:
    path: labs/kustomize
    repoURL: https://github.com/Multpex/k8s-infra
    targetRevision: HEAD
  syncPolicy: {}
